imports:
    - { resource: config.yml }

# parameters:
#     domain.api: 'api.dev.armycreator.net'
#     domain.oauth2: 'oauth2.dev.armycreator.net'
#     domain.website: 'dev.armycreator.net'

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

services: 
    armycreator.dev_routing:
        class: Sitioweb\Bundle\ArmyCreatorBundle\DevRouter
        decorates: router
        decoration_inner_name: router.inner
        arguments:
            - "@router.inner"
            - "@request_stack"
