imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    #trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        server_cost: 165
        forum_sid: %forum_sid%
        donation_parameters: 
            cmd: _s-xclick
            hosted_button_id: L7PK6V4R4LPHG

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            forum:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_forum%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            acl:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_acl%
                user:     %database_user%
                password: %database_password%
            import:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %import_database_name%
                user:     %import_database_user%
                password: %import_database_password%
                charset:  latin1


    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: %kernel.debug%
#       auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    SitiowebArmyCreatorBundle: ~
                    FOSUserBundle: ~
            acl:
                connection: acl
            import:
                connection: import

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    #service: 
    #    user_manager: phpbb_fos_user_manager
    user_class: Sitioweb\Bundle\ArmyCreatorBundle\Entity\User

#elnur_blowfish_password_encoder:
#    cost: 15

knp_menu:
    twig:
        template: armycreator_menu.html.twig

fm_bbcode:
    filter_sets:
        my_default_filter:
            strict: false
            filters: [ default, quote, url, list ]


knp_snappy:
    pdf:
        enabled:    true
        #binary:     /usr/local/bin/wkhtmltopdf
        binary:     weasyprint
        options:
            lowquality: null

m6_statsd:
    servers:
        default:
            address: 'udp://localhost'
            port: 8125
    base_collectors: true
    clients:
        default:
            servers: ['default']
            events:
                kernel.terminate:
                    increment: "website.page_view"
                statsd.memory_usage:
                    gauge: "website.memory"
                statsd.time:
                    timing: "website.time"
                statsd.exception:
                    increment: "website.exception.<value>"
                armycreator.event.collection.contains:
                    increment: "armycreator.collection.<gameCode>.contains"
                armycreator.event.collection.remove:
                    increment: "armycreator.collection.<gameCode>.remove"
                armycreator.event.collection.edit:
                    increment: "armycreator.collection.<gameCode>.edit"
                armycreator.event.squad.new:
                    increment: "armycreator.squad.<gameCode>.new"
                armycreator.event.squad.update:
                    increment: "armycreator.squad.<gameCode>.update"
                armycreator.event.squad.delete:
                    increment: "armycreator.squad.<gameCode>.delete"
                armycreator.event.army.new:
                    increment: "armycreator.army.<gameCode>.new"
                armycreator.event.army.update:
                    increment: "armycreator.army.<gameCode>.update"
                armycreator.event.army.clone:
                    increment: "armycreator.army.<gameCode>.clone"
                armycreator.event.army.delete:
                    increment: "armycreator.army.<gameCode>.delete"
                armycreator.event.squad_line.link:
                    increment: "armycreator.squad_line.<gameCode>.link"
