armycreator_options:
    methods: [OPTIONS]
    path: /{path}
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::empty.html.twig'
    requirements:
        path: "[a-z0-9\-\/]*"


website:
    host: "%domain.website%"
    resource: "routing/website.yml"

fos_oauth_server_token:
    host: "%domain.oauth2%"
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

api:
    host: "%domain.api%"
    resource: "routing/api.yml"


#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
#



#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"


