armycreator_options:
    methods: [OPTIONS]
    path: /{path}
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::empty.html.twig'
    requirements:
        path: "[a-z0-9\\-\\/]*"


website:
    host: "%domain.website%"
    resource: "routing/website.yml"

fos_oauth_server_token:
    host: "%domain.oauth2%"
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

api:
    host: "%domain.api%"
    resource: "routing/api.yml"

