jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: acl

    role_hierarchy:
        ROLE_CONTRIB:     ROLE_USER
        ROLE_CONTRIB_ALL: ROLE_CONTRIB
        ROLE_ADMIN:       ROLE_CONTRIB_ALL
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 15

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: /forum/ucp.php?mode=login
            logout:       true
            anonymous:    true
            switch_user:  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/collection, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/donation, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_CONTRIB }
        - { path: ^/import/, role: ROLE_SUPER_ADMIN }
