services: 
    user_service:
        class: Sitioweb\Bundle\ArmyCreatorBundle\UserService
        arguments:
            - "@security.token_storage"
            - "@fos_user.user_manager"

    armycreator.twig.breed_image_extension: 
        class: Sitioweb\Bundle\ArmyCreatorBundle\Twig\BreedImage
        tags:
            - { name: twig.extension }

    armycreator.twig.squad_extension: 
        class: Sitioweb\Bundle\ArmyCreatorBundle\Twig\Squad
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: twig.extension }


    armycreator.twig.unit_extension: 
        class: Sitioweb\Bundle\ArmyCreatorBundle\Twig\Unit
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@security.token_storage"
        tags:
            - { name: twig.extension }

    armycreator.twig.security: 
        class: Sitioweb\Bundle\ArmyCreatorBundle\Twig\SecurityExtension
        arguments:
            - "@twig.extension.security"
            - "@security.token_storage"
        tags:
            - { name: twig.extension }

    armycreator.twig.user_extension: 
        class: Sitioweb\Bundle\ArmyCreatorBundle\Twig\UserExtension
        arguments:
            - "@user_service"
        tags:
            - { name: twig.extension }

    armycreator.sitemap.listener:
        class: Sitioweb\Bundle\ArmyCreatorBundle\SitemapListener
        arguments:
            - "@router"
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: presta.sitemap.listener }

    armycreator.listener.army_point:
        class: Sitioweb\Bundle\ArmyCreatorBundle\EventListener\ArmyPointListener
        tags :
            - { name: doctrine.event_subscriber, connection: default }

    armycreater.menu_builder:
        class: Sitioweb\Bundle\ArmyCreatorBundle\Menu\Builder
        arguments: 
            - "@knp_menu.factory"
            - "@request_stack"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@user_service"
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: secondMainMenu, alias: secondMain } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: breedShowMenu, alias: breedShow } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: gameMenu, alias: game } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: armyListMenu, alias: armyList } # The alias is what is used to retrieve the menu

    armycreator.security.voter:
        class: Sitioweb\Bundle\ArmyCreatorBundle\Security\ArmyCreatorVoter
        arguments: 
            - "@user_service"
            - "@security.role_hierarchy"
        tags:
            - { name: security.voter }

