Sitioweb\Bundle\ArmyCreatorBundle\Entity\Army:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        description:
            expose: true
        points:
            expose: true
        isShared:
            expose: true

    relations:
        - 
            rel: self
            href:
                route: api_get_army
                parameters:
                    armyId: expr(object.getId())
                absolute: true
