Sitioweb\Bundle\ArmyCreatorBundle\Entity\Squad:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [BaseSquad, ArmyDetail]
        name:
            expose: true
            groups: [BaseSquad, ArmyDetail]

    #relations:
    #    - 
    #        rel: unitType
    #        embedded: 
    #            content: expr(object.getUnitType())

    #    - 
    #        rel: unitType
    #        embedded: 
    #            content: expr(object.getUnitGroup())

    #    - 
    #        rel: unitType
    #        embedded: 
    #            content: expr(object.getSquadLineList())
    relations:
        - 
            rel: self
            href:
                route: api_get_squad
                parameters:
                    squadId: expr(object.getId())
            exclusion:
                groups: [BaseArmy]

        - 
            rel: points
            embedded:
                content: expr(object.getPoints())
            exclusion: 
                groups: [ArmyDetail, BaseSquad, SquadDetail]

        - 
            rel: squad_line_list
            embedded:
                content: expr(object.getSquadLineList())
            exclusion: 
                groups: [BaseSquad, SquadDetail]

        - 
            rel: unit_group
            embedded:
                content: expr(object.getUnitGroup())
            exclusion: 
                groups: [BaseUnit]
