Sitioweb\Bundle\ArmyCreatorBundle\Entity\AbstractUnit:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [BaseUnit]
        name:
            expose: true
            groups: [BaseUnit]



