admin_breed_unitgroup:
    path: /admin/{game}/{breed}/unitGroup
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:unitGroup }

admin_breed_unit:
    path: /admin/{game}/{breed}/unit
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:unit }

admin_breed_unittype:
    path: /admin/{game}/{breed}/unitType
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:unitType }

admin_breed_stuff:
    path: /admin/{game}/{breed}/stuff
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:stuff }

admin_breed_new:
    path: /admin/{game}/new
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:new }

admin_breed_create:
    path: /admin/{game}/breed/create
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:create }
    requirements:
        _methods: POST

admin_breed_edit:
    path: /admin/{game}/{breed}/edit
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:edit }

admin_breed_update:
    path: /admin/{game}/{breed}/update
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:update }
    requirements:
        _methods: POST

admin_breed_delete:
    path: /admin/{game}/{breed}/delete
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:delete }
    requirements:
        _methods: POST

admin_breed:
    path: /admin/{game}/
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:index }

admin_breed_show:
    path: /admin/{game}/{breed}
    defaults: { _controller: SitiowebArmyCreatorBundle:Breed:show }
