admin_game:
    path: /admin/
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:index }

admin_game_new:
    path: /admin/new
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:new }

admin_game_create:
    path: /admin/create
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:create }
    requirements:
        _method: POST

admin_game_stuff:
    path: /admin/{game}/stuff
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:stuff }

admin_game_edit:
    path: /{game}/edit
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:edit }

admin_game_update:
    path: /{code}/update
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:update }
    requirements:
        _method: POST

admin_game_delete:
    path: /{code}/delete
    defaults: { _controller: SitiowebArmyCreatorBundle:Game:delete }
    requirements:
        _method: POST
