api.users:
    type: rest
    resource: "ArmycreatorApiBundle:User"
    name_prefix:  api_

api.user_link:
    type: rest
    resource: "ArmycreatorApiBundle:UserLink"
    name_prefix:  api_
    parent: api.users

api.armies:
    type: rest
    resource: "ArmycreatorApiBundle:Army"
    name_prefix:  api_

api.army_groups:
    type: rest
    resource: "ArmycreatorApiBundle:ArmyGroup"
    name_prefix:  api_
